### ISSUE TITLE
OFFSET and FETCH NEXT clauses

### ISSUE THREAD

**Issue by thelostcode** [ralmsdeveloper/EntityFrameworkCore.FirebirdSQL#20]
### The issue

OFFSET and FETCH FIRST Clauses are not supported by Firebird.

However the base implementation of Linq generates them to the end on Queries if you do

```
Table
   .OrderBy(...)
  .Skip(Any)
  .Take(Any)
```

This results in a statement that cannot be executed. 

Do you have an idea where Entity Framework Core generates this? I am willing to implement it correctly.

**Comment by thelostcode** [comment]
Alright.
I'll found it out. Closing this as I will send you a couple of PR's in a few.

**Comment by thelostcode** [comment]
Well, could you just cherry pick this one to master?

https://github.com/thelostcode/EntityFrameworkCore.FirebirdSQL/commit/4ea167820d9c22c13080337cb886f5b7282547db

**Comment by ralmsdeveloper** [comment]
I'll look at this tomorrow, thank you!

**Comment by ralmsdeveloper** [comment]
Adjusted!
