### ISSUE TITLE
[NOT-AN-ISSUES-ONLY-QUESTION] ;-)

### ISSUE THREAD

**Issue by newdeal30** [ralmsdeveloper/EntityFrameworkCore.FirebirdSQL#30]
Hi!,

One question: 
How is bulk insert done? Do you mean the DbContext.AddRange() function?
Thanks and regards
Michael

**Comment by ralmsdeveloper** [comment]
Hello @newdeal30,
Exactly, however I removed the bulk insert in version 2.1-Preview, I'm working on improvements to 2.1.

I had some bad experiences, so I decided to refactor this.

**Comment by newdeal30** [comment]
Thanks for your quickest response ;-)
I am currently using V2.0.11.6. Is it working there?
What would you do to get faster inserts?
All in one seperate Transaction?
Thanks and regards Michael

**Comment by ralmsdeveloper** [comment]
A 2.0.11.x supports batching.
This is using the EXECUTE BLOCK, to have more performance and send in bulk!

**Comment by newdeal30** [comment]
Thanks!
