### ISSUE TITLE
Issue with Asp.Net Core Identity (DNET-816)

### ISSUE THREAD

**Issue by gpanayotov** [ralmsdeveloper/EntityFrameworkCore.FirebirdSQL#39]
I have issue with Asp.Net Core Identity when it uses EF Core with Firebird database. First I detect it on changing password. I think it will appear always when you update a column which appears in the where clause.
The priblem is the same as in [DNET-816] Wrong EntityFramewordCore command with Asp.Net Core Identity (http://tracker.firebirdsql.org/browse/DNET-816) in the Firebird Tracker

The problem is fixed in (https://github.com/cincuranet/FirebirdSql.Data.FirebirdClient/commit/a9ee29e6a1e72d06044a325f3c7a0aa71a05a1b3)

I have merged this fix in the dev branch. I'm not sure if it breaks something else. At first try it works.
(https://github.com/gpanayotov/EntityFrameworkCore.FirebirdSQL/commit/294b6d6e71cfdce0ddf8b0b17ede4806f7ce92f0)

**Comment by ralmsdeveloper** [comment]
Thanks for watching! 
This week I will be updating and correcting all the problems open here.
Thanks again.

**Comment by ralmsdeveloper** [comment]
@gpanayotov released version 2.1.2, please update and validate if your issue has been resolved with this release.
Thank you!

**Comment by gpanayotov** [comment]
@ralmsdeveloper I've tried 2.1.2 but received exception:
_An item with the same key has already been added. Key: p2_
I will get the latest sources to check where exactly the exception is thrown

**Comment by ralmsdeveloper** [comment]
@gpanayotov 
Could you upload a repro here?
So that I can analyze.

**Comment by ralmsdeveloper** [comment]
I have been able to identify here, I am correcting and unfortunately I will have to make a new version available in the nuget with this correction, I am spending my free time building version 2.2 / 3.0 with all EntityFrameworkCore test base so I avoid these errors.

**Comment by ralmsdeveloper** [comment]
@gpanayotov 
Thanks for helping to identify the problem, corrected with: https://github.com/ralmsdeveloper/EntityFrameworkCore.FirebirdSQL/commit/bab6f69605f2d0f34d43cf47cb6474334ad67560

Updated Nuget Package: 2.1.2.1

**Comment by gpanayotov** [comment]
It works now. Thanks.
